export const enum TransformerTypes {
  APPEND = 'APPEND',
  CAPITALIZE = 'CAPITALIZE',
  ESCAPE_HTML = 'ESCAPE_HTML',
  FLOAT = 'FLOAT',
  INTEGER = 'INTEGER',
  NORMALIZE = 'NORMALIZE',
  PREPEND = 'PREPEND',
  REGEX = 'REGEX',
  REMOVE_NON_NUMERIC = 'REMOVE_NON_NUMERIC',
  REMOVE_NUMERIC = 'REMOVE_NUMERIC',
  REPLACE = 'REPLACE',
  TO_LOWER_CASE = 'TO_LOWER_CASE',
  TO_UPPER_CASE = 'TO_UPPER_CASE',
  TRIM = 'TRIM',
  UNESCAPE_HTML = 'UNESCAPE_HTML'
}
